name: Manual CI Run

on:
  workflow_dispatch:  # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2.0.2
        with:
          bun-version: 1.2.0

      - run: bun install
      - run: bun run build
      - run: bun run package
